[alembic]
script_location = alembic
prepend_sys_path = .
version_path_separator = os

[post_write_hooks]

[loggers]
keys = root,sqlalchemy,alembic

[handlers]

[formatters]

[loggers.root]
level = WARN
handlers =
qualname =

[loggers.sqlalchemy]
level = WARN
handlers =
qualname = sqlalchemy.engine

[loggers.alembic]
level = INFO
handlers =
qualname = alembic

[handler_root]
level = WARN
handler =
qualname =

[keys]