"""initial schema

Revision ID: 001
Revises: 
Create Date: 2024-01-01

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa

revision: str = '001'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_table('users', sa.Column('id', sa.String(), nullable=False), sa.Column('email', sa.String(), nullable=False), sa.Column('password_hash', sa.String(), nullable=False), sa.Column('is_email_verified', sa.Boolean(), nullable=True), sa.Column('status', sa.Enum('PENDING_EMAIL_VERIFICATION', 'ACTIVE', 'SUSPENDED', 'SOFT_DELETED', name='userstatus'), nullable=True), sa.Column('last_login_at', sa.DateTime(), nullable=True), sa.Column('created_at', sa.DateTime(), nullable=True), sa.Column('updated_at', sa.DateTime(), nullable=True), sa.Column('deleted_at', sa.DateTime(), nullable=True), sa.Column('created_by', sa.String(), nullable=True), sa.Column('updated_by', sa.String(), nullable=True), sa.Column('deleted_by', sa.String(), nullable=True), sa.Column('version', sa.String(), nullable=True), primary_key=True)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('roles', sa.Column('id', sa.String(), nullable=False), sa.Column('code', sa.String(), nullable=False), sa.Column('name', sa.String(), nullable=False), sa.Column('description', sa.String(), nullable=True), sa.Column('is_system', sa.Boolean(), nullable=True), sa.Column('created_at', sa.DateTime(), nullable=True), primary_key=True)
    op.create_index(op.f('ix_roles_code'), 'roles', ['code'], unique=True)
    op.create_table('people', sa.Column('id', sa.String(), nullable=False), sa.Column('user_id', sa.String(), nullable=False), sa.Column('first_name', sa.String(), nullable=False), sa.Column('middle_name', sa.String(), nullable=True), sa.Column('last_name', sa.String(), nullable=False), sa.Column('second_last_name', sa.String(), nullable=True), sa.Column('national_id', sa.String(), nullable=False), sa.Column('phone', sa.String(), nullable=False), sa.Column('birth_date', sa.DateTime(), nullable=True), sa.Column('sex', sa.String(), nullable=True), sa.Column('country', sa.String(), nullable=True), sa.Column('province', sa.String(), nullable=True), sa.Column('city', sa.String(), nullable=True), sa.Column('created_at', sa.DateTime(), nullable=True), sa.Column('updated_at', sa.DateTime(), nullable=True), sa.Column('deleted_at', sa.DateTime(), nullable=True), sa.Column('created_by', sa.String(), nullable=True), sa.Column('updated_by', sa.String(), nullable=True), sa.Column('deleted_by', sa.String(), nullable=True), sa.Column('version', sa.String(), nullable=True), primary_key=True)
    op.create_index(op.f('ix_people_user_id'), 'people', ['user_id'], unique=True)
    op.create_index(op.f('ix_people_national_id'), 'people', ['national_id'], unique=True)
    op.create_table('patients', sa.Column('id', sa.String(), nullable=False), sa.Column('user_id', sa.String(), nullable=False), sa.Column('person_id', sa.String(), nullable=False), sa.Column('verification_level', sa.Enum('BASIC', 'IDENTITY_VERIFIED', name='verificationlevel'), nullable=True), sa.Column('emergency_contact_name', sa.String(), nullable=True), sa.Column('emergency_contact_phone', sa.String(), nullable=True), sa.Column('status', sa.Enum('ACTIVE', 'RESTRICTED', 'SUSPENDED', name='patientstatus'), nullable=True), sa.Column('created_at', sa.DateTime(), nullable=True), sa.Column('updated_at', sa.DateTime(), nullable=True), sa.Column('deleted_at', sa.DateTime(), nullable=True), sa.Column('created_by', sa.String(), nullable=True), sa.Column('updated_by', sa.String(), nullable=True), sa.Column('deleted_by', sa.String(), nullable=True), sa.Column('version', sa.String(), nullable=True), primary_key=True)
    op.create_index(op.f('ix_patients_user_id'), 'patients', ['user_id'], unique=True)
    op.create_index(op.f('ix_patients_person_id'), 'patients', ['person_id'], unique=True)
    op.create_table('professionals', sa.Column('id', sa.String(), nullable=False), sa.Column('user_id', sa.String(), nullable=False), sa.Column('person_id', sa.String(), nullable=False), sa.Column('public_slug', sa.String(), nullable=True), sa.Column('professional_type', sa.String(), nullable=True), sa.Column('public_display_name', sa.String(), nullable=True), sa.Column('bio_public', sa.Text(), nullable=True), sa.Column('years_experience', sa.String(), nullable=True), sa.Column('languages_json', sa.String(), nullable=True), sa.Column('onboarding_status', sa.Enum('DRAFT', 'SUBMITTED', 'UNDER_REVIEW', 'APPROVED', 'REJECTED', 'SUSPENDED', name='onboardingstatus'), nullable=True), sa.Column('is_public_profile_enabled', sa.Boolean(), nullable=True), sa.Column('status', sa.Enum('DRAFT', 'PENDING_REVIEW', 'ACTIVE', 'REJECTED', 'SUSPENDED', name='professionalstatus'), nullable=True), sa.Column('created_at', sa.DateTime(), nullable=True), sa.Column('updated_at', sa.DateTime(), nullable=True), sa.Column('deleted_at', sa.DateTime(), nullable=True), sa.Column('created_by', sa.String(), nullable=True), sa.Column('updated_by', sa.String(), nullable=True), sa.Column('deleted_by', sa.String(), nullable=True), sa.Column('version', sa.String(), nullable=True), primary_key=True)
    op.create_index(op.f('ix_professionals_user_id'), 'professionals', ['user_id'], unique=True)
    op.create_index(op.f('ix_professionals_person_id'), 'professionals', ['person_id'], unique=True)
    op.create_index(op.f('ix_professionals_public_slug'), 'professionals', ['public_slug'], unique=True)
    op.create_table('agreements', sa.Column('id', sa.String(), nullable=False), sa.Column('agreement_type', sa.Enum('PLATFORM_TERMS', 'PRIVACY_POLICY', 'PROFESSIONAL_RESPONSIBILITY_AGREEMENT', name='agreementtype'), nullable=False), sa.Column('version_code', sa.String(), nullable=False), sa.Column('title', sa.String(), nullable=False), sa.Column('content_markdown', sa.Text(), nullable=False), sa.Column('is_active', sa.Boolean(), nullable=True), sa.Column('published_at', sa.DateTime(), nullable=True), sa.Column('created_at', sa.DateTime(), nullable=True), sa.Column('updated_at', sa.DateTime(), nullable=True), sa.Column('deleted_at', sa.DateTime(), nullable=True), sa.Column('created_by', sa.String(), nullable=True), sa.Column('updated_by', sa.String(), nullable=True), sa.Column('deleted_by', sa.String(), nullable=True), sa.Column('version', sa.String(), nullable=True), primary_key=True)
    op.create_index(op.f('ix_agreements_agreement_type'), 'agreements', ['agreement_type'], unique=False)
    op.create_table('files', sa.Column('id', sa.String(), nullable=False), sa.Column('storage_backend', sa.Enum('LOCAL', name='storagebackend'), nullable=True), sa.Column('relative_path', sa.String(), nullable=False), sa.Column('original_filename', sa.String(), nullable=False), sa.Column('mime_type', sa.String(), nullable=False), sa.Column('size_bytes', sa.String(), nullable=False), sa.Column('sha256', sa.String(), nullable=False), sa.Column('is_encrypted', sa.String(), nullable=True), sa.Column('access_level', sa.Enum('PUBLIC', 'PRIVATE', 'SENSITIVE', name='accesslevel'), nullable=True), sa.Column('owner_user_id', sa.String(), nullable=True), sa.Column('created_at', sa.DateTime(), nullable=True), sa.Column('deleted_at', sa.DateTime(), nullable=True), sa.Column('deleted_by', sa.String(), nullable=True), primary_key=True)
    op.create_table('audit_events', sa.Column('id', sa.String(), nullable=False), sa.Column('occurred_at', sa.DateTime(), nullable=True), sa.Column('actor_user_id', sa.String(), nullable=True), sa.Column('actor_role_code', sa.String(), nullable=True), sa.Column('action', sa.String(), nullable=False), sa.Column('entity_type', sa.String(), nullable=False), sa.Column('entity_id', sa.String(), nullable=False), sa.Column('request_id', sa.String(), nullable=True), sa.Column('ip_address', sa.String(), nullable=True), sa.Column('user_agent', sa.String(), nullable=True), sa.Column('before_json', sa.Text(), nullable=True), sa.Column('after_json', sa.Text(), nullable=True), sa.Column('justification', sa.Text(), nullable=True), sa.Column('severity', sa.Enum('INFO', 'WARNING', 'CRITICAL', name='severity'), nullable=True), sa.Column('created_at', sa.DateTime(), nullable=True), primary_key=True)
    op.create_index(op.f('ix_audit_events_occurred_at'), 'audit_events', ['occurred_at'], unique=False)
    op.create_index(op.f('ix_audit_events_actor_user_id'), 'audit_events', ['actor_user_id'], unique=False)
    op.create_index(op.f('ix_audit_events_action'), 'audit_events', ['action'], unique=False)
    op.create_index(op.f('ix_audit_events_entity_type'), 'audit_events', ['entity_type'], unique=False)
    op.create_index(op.f('ix_audit_events_entity_id'), 'audit_events', ['entity_id'], unique=False)
    op.create_table('user_roles', sa.Column('id', sa.String(), nullable=False), sa.Column('user_id', sa.String(), nullable=False), sa.Column('role_id', sa.String(), nullable=False), sa.Column('assigned_at', sa.DateTime(), nullable=True), sa.Column('assigned_by', sa.String(), nullable=True), sa.Column('revoked_at', sa.DateTime(), nullable=True), sa.Column('revoked_by', sa.String(), nullable=True), sa.Column('status', sa.Enum('ACTIVE', 'REVOKED', name='userrolestatus'), nullable=True), primary_key=True)
    op.create_index(op.f('ix_user_roles_user_id'), 'user_roles', ['user_id'], unique=False)
    op.create_index(op.f('ix_user_roles_role_id'), 'user_roles', ['role_id'], unique=False)
    op.create_table('professional_credentials', sa.Column('id', sa.String(), nullable=False), sa.Column('professional_id', sa.String(), nullable=False), sa.Column('credential_type', sa.Enum('TITLE', 'LICENSE', 'SPECIALTY', 'COURSE', 'OTHER', name='credentialtype'), nullable=False), sa.Column('title', sa.String(), nullable=False), sa.Column('issuing_entity', sa.String(), nullable=False), sa.Column('credential_number', sa.String(), nullable=True), sa.Column('issue_date', sa.DateTime(), nullable=True), sa.Column('expiry_date', sa.DateTime(), nullable=True), sa.Column('verified_status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='verifiedstatus'), nullable=True), sa.Column('notes', sa.Text(), nullable=True), sa.Column('created_at', sa.DateTime(), nullable=True), sa.Column('updated_at', sa.DateTime(), nullable=True), sa.Column('deleted_at', sa.DateTime(), nullable=True), sa.Column('created_by', sa.String(), nullable=True), sa.Column('updated_by', sa.String(), nullable=True), sa.Column('deleted_by', sa.String(), nullable=True), sa.Column('version', sa.String(), nullable=True), primary_key=True)
    op.create_index(op.f('ix_professional_credentials_professional_id'), 'professional_credentials', ['professional_id'], unique=False)
    op.create_table('professional_documents', sa.Column('id', sa.String(), nullable=False), sa.Column('professional_id', sa.String(), nullable=False), sa.Column('document_type', sa.Enum('NATIONAL_ID_FRONT', 'NATIONAL_ID_BACK', 'DEGREE', 'REGISTRATION_CERTIFICATE', 'SELFIE_VERIFICATION', 'CV', 'SIGNED_AGREEMENT', 'SUPPORTING_DOCUMENT', name='documenttype'), nullable=False), sa.Column('file_id', sa.String(), nullable=False), sa.Column('original_filename', sa.String(), nullable=False), sa.Column('mime_type', sa.String(), nullable=False), sa.Column('sha256', sa.String(), nullable=False), sa.Column('uploaded_at', sa.DateTime(), nullable=True), sa.Column('review_status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='reviewstatus'), nullable=True), sa.Column('review_notes', sa.Text(), nullable=True), sa.Column('created_at', sa.DateTime(), nullable=True), sa.Column('updated_at', sa.DateTime(), nullable=True), sa.Column('deleted_at', sa.DateTime(), nullable=True), sa.Column('created_by', sa.String(), nullable=True), sa.Column('updated_by', sa.String(), nullable=True), sa.Column('deleted_by', sa.String(), nullable=True), sa.Column('version', sa.String(), nullable=True), primary_key=True)
    op.create_index(op.f('ix_professional_documents_professional_id'), 'professional_documents', ['professional_id'], unique=False)
    op.create_table('agreement_acceptances', sa.Column('id', sa.String(), nullable=False), sa.Column('agreement_id', sa.String(), nullable=False), sa.Column('user_id', sa.String(), nullable=False), sa.Column('accepted_at', sa.DateTime(), nullable=True), sa.Column('acceptance_type', sa.Enum('CLICKWRAP', 'ELECTRONIC_SIGNATURE', 'EQUIVALENT_FORMAL_MECHANISM', name='acceptancetype'), nullable=False), sa.Column('ip_address', sa.String(), nullable=True), sa.Column('user_agent', sa.String(), nullable=True), sa.Column('evidence_file_id', sa.String(), nullable=True), sa.Column('status', sa.Enum('ACCEPTED', 'REVOKED', name='agreementacceptancestatus'), nullable=True), sa.Column('created_at', sa.DateTime(), nullable=True), sa.Column('updated_at', sa.DateTime(), nullable=True), sa.Column('deleted_at', sa.DateTime(), nullable=True), sa.Column('created_by', sa.String(), nullable=True), sa.Column('updated_by', sa.String(), nullable=True), sa.Column('deleted_by', sa.String(), nullable=True), sa.Column('version', sa.String(), nullable=True), primary_key=True)
    op.create_index(op.f('ix_agreement_acceptances_agreement_id'), 'agreement_acceptances', ['agreement_id'], unique=False)
    op.create_index(op.f('ix_agreement_acceptances_user_id'), 'agreement_acceptances', ['user_id'], unique=False)
    op.create_table('verification_requests', sa.Column('id', sa.String(), nullable=False), sa.Column('professional_id', sa.String(), nullable=False), sa.Column('submitted_at', sa.DateTime(), nullable=True), sa.Column('assigned_admin_id', sa.String(), nullable=True), sa.Column('status', sa.Enum('SUBMITTED', 'UNDER_REVIEW', 'APPROVED', 'REJECTED', 'NEEDS_CORRECTION', 'SUSPENDED', name='verificationrequeststatus'), nullable=True), sa.Column('decision_at', sa.DateTime(), nullable=True), sa.Column('decision_reason', sa.Text(), nullable=True), sa.Column('reviewed_by', sa.String(), nullable=True), sa.Column('created_at', sa.DateTime(), nullable=True), sa.Column('updated_at', sa.DateTime(), nullable=True), sa.Column('deleted_at', sa.DateTime(), nullable=True), sa.Column('created_by', sa.String(), nullable=True), sa.Column('updated_by', sa.String(), nullable=True), sa.Column('deleted_by', sa.String(), nullable=True), sa.Column('version', sa.String(), nullable=True), primary_key=True)
    op.create_index(op.f('ix_verification_requests_professional_id'), 'verification_requests', ['professional_id'], unique=False)
    op.create_table('verification_events', sa.Column('id', sa.String(), nullable=False), sa.Column('verification_request_id', sa.String(), nullable=False), sa.Column('event_type', sa.Enum('SUBMITTED', 'ASSIGNED', 'COMMENT_ADDED', 'DOCUMENT_APPROVED', 'DOCUMENT_REJECTED', 'APPROVED', 'REJECTED', 'CORRECTION_REQUESTED', 'SUSPENDED', name='verificationeventtype'), nullable=False), sa.Column('event_payload_json', sa.Text(), nullable=True), sa.Column('created_at', sa.DateTime(), nullable=True), sa.Column('created_by', sa.String(), nullable=True), primary_key=True)
    op.create_index(op.f('ix_verification_events_verification_request_id'), 'verification_events', ['verification_request_id'], unique=False)
    op.create_table('file_permissions', sa.Column('id', sa.String(), nullable=False), sa.Column('file_id', sa.String(), nullable=False), sa.Column('subject_type', sa.Enum('USER', 'ROLE', name='subjecttype'), nullable=False), sa.Column('subject_id', sa.String(), nullable=False), sa.Column('permission', sa.Enum('READ', 'WRITE', 'DELETE', 'GRANT', name='permission'), nullable=False), sa.Column('granted_by', sa.String(), nullable=True), sa.Column('expires_at', sa.DateTime(), nullable=True), sa.Column('created_at', sa.DateTime(), nullable=True), primary_key=True)
    op.create_index(op.f('ix_file_permissions_file_id'), 'file_permissions', ['file_id'], unique=False)
    op.create_table('exceptional_access_requests', sa.Column('id', sa.String(), nullable=False), sa.Column('requester_user_id', sa.String(), nullable=False), sa.Column('target_user_id', sa.String(), nullable=True), sa.Column('resource_type', sa.String(), nullable=False), sa.Column('resource_id', sa.String(), nullable=True), sa.Column('reason', sa.Text(), nullable=False), sa.Column('patient_authorization_file_id', sa.String(), nullable=True), sa.Column('status', sa.Enum('REQUESTED', 'APPROVED', 'REJECTED', 'EXPIRED', 'REVOKED', name='exceptionalaccessstatus'), nullable=True), sa.Column('approved_by', sa.String(), nullable=True), sa.Column('approved_at', sa.DateTime(), nullable=True), sa.Column('expires_at', sa.DateTime(), nullable=True), sa.Column('created_at', sa.DateTime(), nullable=True), sa.Column('updated_at', sa.DateTime(), nullable=True), sa.Column('deleted_at', sa.DateTime(), nullable=True), sa.Column('created_by', sa.String(), nullable=True), sa.Column('updated_by', sa.String(), nullable=True), sa.Column('deleted_by', sa.String(), nullable=True), sa.Column('version', sa.String(), nullable=True), primary_key=True)
    op.create_index(op.f('ix_exceptional_access_requests_requester_user_id'), 'exceptional_access_requests', ['requester_user_id'], unique=False)
    op.create_table('system_parameters', sa.Column('id', sa.String(), nullable=False), sa.Column('key', sa.String(), nullable=False), sa.Column('value_json', sa.Text(), nullable=False), sa.Column('description', sa.String(), nullable=True), sa.Column('is_secret', sa.String(), nullable=True), sa.Column('created_at', sa.DateTime(), nullable=True), sa.Column('updated_at', sa.DateTime(), nullable=True), primary_key=True)
    op.create_index(op.f('ix_system_parameters_key'), 'system_parameters', ['key'], unique=True)
    op.create_table('feature_flags', sa.Column('id', sa.String(), nullable=False), sa.Column('code', sa.String(), nullable=False), sa.Column('enabled', sa.String(), nullable=True), sa.Column('description', sa.String(), nullable=True), sa.Column('created_at', sa.DateTime(), nullable=True), sa.Column('updated_at', sa.DateTime(), nullable=True), primary_key=True)
    op.create_index(op.f('ix_feature_flags_code'), 'feature_flags', ['code'], unique=True)
    op.create_table('entity_versions', sa.Column('id', sa.String(), nullable=False), sa.Column('entity_type', sa.String(), nullable=False), sa.Column('entity_id', sa.String(), nullable=False), sa.Column('version', sa.String(), nullable=False), sa.Column('changed_by', sa.String(), nullable=True), sa.Column('changed_at', sa.DateTime(), nullable=True), sa.Column('change_type', sa.String(), nullable=False), sa.Column('before_json', sa.Text(), nullable=True), sa.Column('after_json', sa.Text(), nullable=True), primary_key=True)
    op.create_index(op.f('ix_entity_versions_entity_type'), 'entity_versions', ['entity_type'], unique=False)
    op.create_index(op.f('ix_entity_versions_entity_id'), 'entity_versions', ['entity_id'], unique=False)


def downgrade() -> None:
    op.drop_table('entity_versions')
    op.drop_table('feature_flags')
    op.drop_table('system_parameters')
    op.drop_table('exceptional_access_requests')
    op.drop_table('file_permissions')
    op.drop_table('verification_events')
    op.drop_table('verification_requests')
    op.drop_table('agreement_acceptances')
    op.drop_table('professional_documents')
    op.drop_table('professional_credentials')
    op.drop_table('user_roles')
    op.drop_table('audit_events')
    op.drop_table('files')
    op.drop_table('agreements')
    op.drop_table('professionals')
    op.drop_table('patients')
    op.drop_table('people')
    op.drop_table('roles')
    op.drop_table('users')